default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: ipsy_music_db
  username: root
  password: ipsyMusicIsTheBest
  host: db

test:
  <<: *default
  database: ipsyapi_test

production:
  <<: *default
  database: ipsyapi_production
  username: ipsyapi
  password: <%= ENV['IPSYAPI_DATABASE_PASSWORD'] %>
